In [1]:
import numpy as np

In [2]:
a= [1, 4, 5, 6]



In [3]:
print(type(a))

<class 'list'>


In [7]:
arr= np.array(a)
arr

array([1, 4, 5, 6])

In [9]:
arr.shape

(4,)

In [11]:
arr.dtype

dtype('int32')

In [12]:
arr.ndim

1

In [17]:
np.random.random((2,3))

array([[7.62406282e-04, 1.67941589e-01, 4.56957934e-01],
       [5.44526723e-01, 7.60732476e-01, 8.07990932e-01]])

In [18]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [20]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [27]:
np.full_like((3,2), [0,1])

array([0, 1])

In [29]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

## Modeule 2 data wrangling and viz


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
#Pandas can connect to databases, get data with queries and save in a dataframe.
url='https://github.com/WalePhenomenon/climate_change/blob/master/fuel_ferc1.csv?raw=true'
fuel_data = pd.read_csv(url, on_bad_lines='skip')
fuel_data.describe(include='all')


record_id  utility_id_ferc1   report_year  \
count                   29523      29523.000000  29523.000000   
unique                  29523               NaN           NaN   
top     f1_fuel_1994_12_1_0_7               NaN           NaN   
freq                        1               NaN           NaN   
mean                      NaN        118.601836   2005.806050   
std                       NaN         74.178353      7.025483   
min                       NaN          1.000000   1994.000000   
25%                       NaN         55.000000   2000.000000   
50%                       NaN        122.000000   2006.000000   
75%                       NaN        176.000000   2012.000000   
max                       NaN        514.000000   2018.000000   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
count             29523               29523     29343     2.952300e+04   
unique             2315                   6         9              NaN   
top           big stone                 gas       mcf              NaN   
freq                156               11486     11354              NaN   
mean                NaN                 NaN       NaN     2.622119e+06   
std                 NaN                 NaN       NaN     9.118004e+06   
min                 NaN                 NaN       NaN     1.000000e+00   
25%                 NaN                 NaN       NaN     1.381700e+04   
50%                 NaN                 NaN       NaN     2.533220e+05   
75%                 NaN                 NaN       NaN     1.424034e+06   
max                 NaN                 NaN       NaN     5.558942e+08   

        fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
count          29523.000000               29523.000000   
unique                  NaN                        NaN   
top                     NaN                        NaN   
freq                    NaN                        NaN   
mean               8.492111                 208.649031   
std               10.600220                2854.490090   
min                0.000001                -276.080000   
25%                1.024000                   5.207000   
50%                5.762694                  26.000000   
75%               17.006000                  47.113000   
max              341.260000              139358.000000   

        fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
count                   2.952300e+04         29523.000000  
unique                           NaN                  NaN  
top                              NaN                  NaN  
freq                             NaN                  NaN  
mean                    9.175704e+02            19.304354  
std                     6.877593e+04          2091.540939  
min                    -8.749370e+02           -41.501000  
25%                     3.778500e+00             1.940000  
50%                     1.737100e+01             4.127000  
75%                     4.213700e+01             7.745000  
max                     7.964521e+06        359278.000000

In [6]:
fuel_data.isna().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [7]:
fuel_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29523 entries, 0 to 29522
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   record_id                     29523 non-null  object 
 1   utility_id_ferc1              29523 non-null  int64  
 2   report_year                   29523 non-null  int64  
 3   plant_name_ferc1              29523 non-null  object 
 4   fuel_type_code_pudl           29523 non-null  object 
 5   fuel_unit                     29343 non-null  object 
 6   fuel_qty_burned               29523 non-null  float64
 7   fuel_mmbtu_per_unit           29523 non-null  float64
 8   fuel_cost_per_unit_burned     29523 non-null  float64
 9   fuel_cost_per_unit_delivered  29523 non-null  float64
 10  fuel_cost_per_mmbtu           29523 non-null  float64
dtypes: float64(5), int64(2), object(4)
memory usage: 2.5+ MB


In [8]:
fuel_data.groupby('fuel_unit')['fuel_unit'].count()

fuel_unit
bbl        7998
gal          84
gramsU      464
kgU         110
mcf       11354
mmbtu       180
mwdth        95
mwhth       100
ton        8958
Name: fuel_unit, dtype: int64